databases:
  - name: mysitedb
    plan: free
    databaseName: mysite
    user: mysite

services:
  - type: web
    plan: free
    name: movie_theater_booking
    runtime: python
    buildCommand: 'bash ./homework2/build.sh'
    startCommand: 'python -m gunicorn --chdir ./homework2 movie_theater_booking.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4