# Generated by Django 5.2.6 on 2025-10-05 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_theater_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='movie',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='movie_theater_booking.movie'),
            preserve_default=False,
        ),
    ]
